part of evil_icons_flutter;

abstract class EvilIcons {
  // See https://github.com/tvc12/evil_icons_flutter
  // See http://evil-icons.io/

  static const EvilIconData archive = EvilIconData(0xf100);
  static const EvilIconData arrow_down = EvilIconData(0xf101);
  static const EvilIconData arrow_left = EvilIconData(0xf102);
  static const EvilIconData arrow_right = EvilIconData(0xf103);
  static const EvilIconData arrow_up = EvilIconData(0xf104);
  static const EvilIconData bell = EvilIconData(0xf105);
  static const EvilIconData calendar = EvilIconData(0xf106);
  static const EvilIconData camera = EvilIconData(0xf107);
  static const EvilIconData cart = EvilIconData(0xf108);
  static const EvilIconData chart = EvilIconData(0xf109);
  static const EvilIconData check = EvilIconData(0xf10a);
  static const EvilIconData chevron_down = EvilIconData(0xf10b);
  static const EvilIconData fchevron_left = EvilIconData(0xf10c);
  static const EvilIconData chevron_right = EvilIconData(0xf10d);
  static const EvilIconData chevron_up = EvilIconData(0xf10e);
  static const EvilIconData clock = EvilIconData(0xf10f);
  static const EvilIconData close = EvilIconData(0xf110);
  static const EvilIconData close_o = EvilIconData(0xf111);
  static const EvilIconData comment = EvilIconData(0xf112);
  static const EvilIconData credit_card = EvilIconData(0xf113);
  static const EvilIconData envelope = EvilIconData(0xf114);
  static const EvilIconData exclamation = EvilIconData(0xf115);
  static const EvilIconData external_link = EvilIconData(0xf116);
  static const EvilIconData eye = EvilIconData(0xf117);
  static const EvilIconData gear = EvilIconData(0xf118);
  static const EvilIconData heart = EvilIconData(0xf119);
  static const EvilIconData image = EvilIconData(0xf11a);
  static const EvilIconData like = EvilIconData(0xf11b);
  static const EvilIconData link = EvilIconData(0xf11c);
  static const EvilIconData location = EvilIconData(0xf11d);
  static const EvilIconData lock = EvilIconData(0xf11e);
  static const EvilIconData minus = EvilIconData(0xf11f);
  static const EvilIconData navicon = EvilIconData(0xf120);
  static const EvilIconData paperclip = EvilIconData(0xf121);
  static const EvilIconData pencil = EvilIconData(0xf122);
  static const EvilIconData play = EvilIconData(0xf123);
  static const EvilIconData plus = EvilIconData(0xf124);
  static const EvilIconData pointer = EvilIconData(0xf125);
  static const EvilIconData question = EvilIconData(0xf126);
  static const EvilIconData redo = EvilIconData(0xf127);
  static const EvilIconData refresh = EvilIconData(0xf128);
  static const EvilIconData retweet = EvilIconData(0xf129);
  static const EvilIconData sc_facebook = EvilIconData(0xf12a);
  static const EvilIconData sc_github = EvilIconData(0xf12b);
  static const EvilIconData sc_google_plus = EvilIconData(0xf12c);
  static const EvilIconData sc_instagram = EvilIconData(0xf12d);
  static const EvilIconData sc_linkedin = EvilIconData(0xf12e);
  static const EvilIconData sc_odnoklassniki = EvilIconData(0xf12f);
  static const EvilIconData sc_pinterest = EvilIconData(0xf130);
  static const EvilIconData sc_skype = EvilIconData(0xf131);
  static const EvilIconData sc_soundcloud = EvilIconData(0xf132);
  static const EvilIconData sc_telegram = EvilIconData(0xf133);
  static const EvilIconData sc_tumblr = EvilIconData(0xf134);
  static const EvilIconData sc_twitter = EvilIconData(0xf135);
  static const EvilIconData sc_vimeo = EvilIconData(0xf136);
  static const EvilIconData sc_vk = EvilIconData(0xf137);
  static const EvilIconData sc_youtube = EvilIconData(0xf138);
  static const EvilIconData search = EvilIconData(0xf139);
  static const EvilIconData share_apple = EvilIconData(0xf13a);
  static const EvilIconData share_google = EvilIconData(0xf13b);
  static const EvilIconData spinner = EvilIconData(0xf13c);
  static const EvilIconData spinner_2 = EvilIconData(0xf13d);
  static const EvilIconData spinner_3 = EvilIconData(0xf13e);
  static const EvilIconData star = EvilIconData(0xf13f);
  static const EvilIconData tag = EvilIconData(0xf140);
  static const EvilIconData trash = EvilIconData(0xf141);
  static const EvilIconData trophy = EvilIconData(0xf142);
  static const EvilIconData undo = EvilIconData(0xf143);
  static const EvilIconData unlock = EvilIconData(0xf144);
  static const EvilIconData user = EvilIconData(0xf145);
}
