library evil_icons_flutter;

import 'package:evil_icons_flutter/evil_icons_data.dart';
import 'package:flutter/widgets.dart';

class EvilIcons {
  EvilIcons._();
  // See https://github.com/tvc12/evil_icons_flutter
  // See http://evil-icons.io/

  static const IconData archive = EvilIconData(0xf100);
  static const IconData arrow_down = EvilIconData(0xf101);
  static const IconData arrow_left = EvilIconData(0xf102);
  static const IconData arrow_right = EvilIconData(0xf103);
  static const IconData arrow_up = EvilIconData(0xf104);
  static const IconData bell = EvilIconData(0xf105);
  static const IconData calendar = EvilIconData(0xf106);
  static const IconData camera = EvilIconData(0xf107);
  static const IconData cart = EvilIconData(0xf108);
  static const IconData chart = EvilIconData(0xf109);
  static const IconData check = EvilIconData(0xf10a);
  static const IconData chevron_down = EvilIconData(0xf10b);
  static const IconData chevron_left = EvilIconData(0xf10c);
  static const IconData chevron_right = EvilIconData(0xf10d);
  static const IconData chevron_up = EvilIconData(0xf10e);
  static const IconData clock = EvilIconData(0xf10f);
  static const IconData close = EvilIconData(0xf110);
  static const IconData close_o = EvilIconData(0xf111);
  static const IconData comment = EvilIconData(0xf112);
  static const IconData credit_card = EvilIconData(0xf113);
  static const IconData envelope = EvilIconData(0xf114);
  static const IconData exclamation = EvilIconData(0xf115);
  static const IconData external_link = EvilIconData(0xf116);
  static const IconData eye = EvilIconData(0xf117);
  static const IconData gear = EvilIconData(0xf118);
  static const IconData heart = EvilIconData(0xf119);
  static const IconData image = EvilIconData(0xf11a);
  static const IconData like = EvilIconData(0xf11b);
  static const IconData link = EvilIconData(0xf11c);
  static const IconData location = EvilIconData(0xf11d);
  static const IconData lock = EvilIconData(0xf11e);
  static const IconData minus = EvilIconData(0xf11f);
  static const IconData navicon = EvilIconData(0xf120);
  static const IconData paperclip = EvilIconData(0xf121);
  static const IconData pencil = EvilIconData(0xf122);
  static const IconData play = EvilIconData(0xf123);
  static const IconData plus = EvilIconData(0xf124);
  static const IconData pointer = EvilIconData(0xf125);
  static const IconData question = EvilIconData(0xf126);
  static const IconData redo = EvilIconData(0xf127);
  static const IconData refresh = EvilIconData(0xf128);
  static const IconData retweet = EvilIconData(0xf129);
  static const IconData sc_facebook = EvilIconData(0xf12a);
  static const IconData sc_github = EvilIconData(0xf12b);
  static const IconData sc_google_plus = EvilIconData(0xf12c);
  static const IconData sc_instagram = EvilIconData(0xf12d);
  static const IconData sc_linkedin = EvilIconData(0xf12e);
  static const IconData sc_odnoklassniki = EvilIconData(0xf12f);
  static const IconData sc_pinterest = EvilIconData(0xf130);
  static const IconData sc_skype = EvilIconData(0xf131);
  static const IconData sc_soundcloud = EvilIconData(0xf132);
  static const IconData sc_telegram = EvilIconData(0xf133);
  static const IconData sc_tumblr = EvilIconData(0xf134);
  static const IconData sc_twitter = EvilIconData(0xf135);
  static const IconData sc_vimeo = EvilIconData(0xf136);
  static const IconData sc_vk = EvilIconData(0xf137);
  static const IconData sc_youtube = EvilIconData(0xf138);
  static const IconData search = EvilIconData(0xf139);
  static const IconData share_apple = EvilIconData(0xf13a);
  static const IconData share_google = EvilIconData(0xf13b);
  static const IconData spinner = EvilIconData(0xf13c);
  static const IconData spinner_2 = EvilIconData(0xf13d);
  static const IconData spinner_3 = EvilIconData(0xf13e);
  static const IconData star = EvilIconData(0xf13f);
  static const IconData tag = EvilIconData(0xf140);
  static const IconData trash = EvilIconData(0xf141);
  static const IconData trophy = EvilIconData(0xf142);
  static const IconData undo = EvilIconData(0xf143);
  static const IconData unlock = EvilIconData(0xf144);
  static const IconData user = EvilIconData(0xf145);
}
